permalink: /:year:month:day/:title
url: td00.github.io #Your url here
baseurl: /launch

# variables
name: td00
description: td00-desc
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
